# Generated by Django 3.2.6 on 2021-11-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_id', models.CharField(max_length=20)),
                ('admin_email', models.CharField(max_length=40)),
                ('admin_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Housekeeper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('housekeeper_id', models.CharField(max_length=20)),
                ('housekeeper_name', models.CharField(max_length=30)),
                ('housekeeper_email', models.CharField(max_length=40)),
                ('housekeeper_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room_floor',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=15)),
                ('room_reservation_info', models.CharField(max_length=20)),
                ('room_occupancy', models.CharField(max_length=15)),
                ('room_status', models.CharField(max_length=15)),
                ('room_notes', models.CharField(max_length=250)),
                ('room_updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('room_housekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_app.housekeeper')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_app.room')),
                ('room_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_app.admin')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='floor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_app.room_floor'),
        ),
    ]
