# Generated by Django 3.2.6 on 2021-11-20 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0003_alter_room_floor_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='Room',
        ),
        migrations.AlterModelTable(
            name='room_floor',
            table='Room_floor',
        ),
    ]
