# Generated by Django 3.2.6 on 2021-11-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0004_auto_20211121_0506'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
        migrations.AlterModelTable(
            name='room_floor',
            table=None,
        ),
    ]
