# Generated by Django 3.2.6 on 2021-11-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0007_housekeeper_details_housekeeper_room_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeper_details',
            name='housekeeper_room_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_app.room'),
        ),
        migrations.DeleteModel(
            name='Housekeeper_room_visit',
        ),
    ]
