# Generated by Django 3.2.6 on 2021-11-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0008_auto_20211122_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeper_details',
            name='housekeeper_room_visit',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='hms_app.room'),
        ),
    ]
