# Generated by Django 3.2.6 on 2021-11-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0010_auto_20211122_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_details',
            name='room_housekeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hms_app.housekeeper'),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_inspect_status',
            field=models.CharField(default='Inspected', max_length=20),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_notes',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_occupancy',
            field=models.CharField(default='Vacant', max_length=20),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_reservation_info',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
