# Generated by Django 3.2.6 on 2021-11-22 23:12

from django.db import migrations, models
import hms_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0011_auto_20211123_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=20)),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_email', models.CharField(max_length=40)),
                ('staff_password', models.CharField(max_length=30)),
                ('staff_mobile', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_updated_by',
            field=models.ForeignKey(on_delete=hms_app.models.Admin, to='hms_app.staff'),
        ),
    ]
