# Generated by Django 3.2.6 on 2021-11-22 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0014_alter_room_details_room_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_details',
            name='room_updated_by_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.staff'),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_housekeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.housekeeper'),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.admin'),
        ),
    ]
