# Generated by Django 3.2.6 on 2021-11-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0015_auto_20211123_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_details',
            name='room_updated_by_staff',
        ),
    ]
