# Generated by Django 3.2.6 on 2021-11-23 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0016_remove_room_details_room_updated_by_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_drinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food_quentity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quentity', models.CharField(max_length=20)),
                ('food_drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_app.food_drinks')),
            ],
        ),
        migrations.CreateModel(
            name='Food_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room_service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_quentity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.food_quentity')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.food_drinks')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_app.room')),
            ],
        ),
        migrations.AddField(
            model_name='food_drinks',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_app.food_type'),
        ),
    ]
