# Generated by Django 3.2.6 on 2021-11-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0017_auto_20211123_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_quentity',
            name='food_drinks',
        ),
        migrations.AddField(
            model_name='food_quentity',
            name='food_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hms_app.food_type'),
            preserve_default=False,
        ),
    ]
