# Generated by Django 3.2.6 on 2021-11-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0018_auto_20211123_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_service',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
