# Generated by Django 3.2.6 on 2021-11-23 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0019_room_service_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_order_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.food_drinks')),
                ('quentity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.food_quentity')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.room')),
            ],
        ),
    ]
