# Generated by Django 3.2.6 on 2021-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0020_food_order_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_service',
            name='room_scervice_updated_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_updated_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_updated_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room_service',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
