# Generated by Django 3.2.6 on 2021-11-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0021_auto_20211125_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_service',
            name='order_status',
            field=models.CharField(default='Under-Cooking', max_length=20),
        ),
        migrations.AddField(
            model_name='room_service',
            name='order_taken_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
