# Generated by Django 3.2.6 on 2021-11-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0023_auto_20211125_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_service',
            name='show_details',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
