# Generated by Django 3.2.6 on 2021-11-24 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0024_room_service_show_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_complaints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complaints', models.CharField(max_length=255)),
                ('complaints_taken_by', models.CharField(max_length=50)),
                ('complaints_by', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(default='Review', max_length=20)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.room')),
            ],
        ),
    ]
