# Generated by Django 3.2.6 on 2021-11-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0025_customer_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=50)),
            ],
        ),
    ]
