# Generated by Django 3.2.6 on 2021-11-25 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0026_daily_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeping_daily_activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=10)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.daily_activities')),
            ],
        ),
    ]
