# Generated by Django 3.2.6 on 2021-11-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0027_housekeeping_daily_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_activities',
            name='time',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='housekeeping_daily_activity',
            name='time',
            field=models.CharField(default='00000000', max_length=10),
        ),
    ]
