# Generated by Django 3.2.6 on 2021-11-25 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0028_auto_20211125_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeping_daily_activity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_app.daily_activities'),
        ),
    ]
