# Generated by Django 3.2.6 on 2021-11-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0029_alter_housekeeping_daily_activity_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.staff_type'),
        ),
    ]
