# Generated by Django 3.2.6 on 2021-11-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0032_alter_room_floor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_details',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.room'),
        ),
    ]
