# Generated by Django 3.2.6 on 2021-11-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0033_alter_room_details_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.room_floor'),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hms_app.room'),
        ),
    ]
