# Generated by Django 3.2.6 on 2021-11-26 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0034_auto_20211127_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.room_floor'),
        ),
    ]
