# Generated by Django 3.2.6 on 2021-11-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0035_alter_room_floor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_complaints',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.room'),
        ),
        migrations.AlterField(
            model_name='food_drinks',
            name='food_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.food_type'),
        ),
        migrations.AlterField(
            model_name='food_order_list',
            name='food_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.food_drinks'),
        ),
        migrations.AlterField(
            model_name='food_order_list',
            name='quentity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.food_quentity'),
        ),
        migrations.AlterField(
            model_name='food_order_list',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.room'),
        ),
        migrations.AlterField(
            model_name='food_quentity',
            name='food_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.food_type'),
        ),
        migrations.AlterField(
            model_name='housekeeper_room_visit',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.room'),
        ),
        migrations.AlterField(
            model_name='housekeeping_daily_activity',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.daily_activities'),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_housekeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.housekeeper'),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.room'),
        ),
        migrations.AlterField(
            model_name='room_service',
            name='food_list_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.food_order_list'),
        ),
        migrations.AlterField(
            model_name='room_service',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms_app.room'),
        ),
    ]
